{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "homarr.fullname" . }}
  annotations:
    {{- with ( .Values.ingress.annotations) }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
     {{- include "homarr.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}

  {{- if .Values.ingress.tls }}
  tls: 
  {{- toYaml .Values.ingress.tls | nindent 2}}
  {{- end }}

  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: {{ default "" .Values.ingress.path }}
        pathType: {{ .Values.ingress.pathType }}
        backend:
          service:
            name: {{ include "homarr.fullname" . }}
            port:
              number: {{ default 80 .Values.service.port }}

{{- end }}