{{- if .Values.homarr.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  {{ include "homarr.fullname" . }}
spec:
  accessModes:
    -  {{ .Values.homarr.persistence.accessMode }}
  storageClassName: {{ .Values.homarr.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.homarr.persistence.size }}
{{- end }}