{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "homarr.fullname" . }}
  annotations:
    {{- with ( .Values.service.annotations) }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- $type := default "ClusterIP" .Values.service.type }}
  type: {{ $type }}
  selector:
    {{- include "homarr.labelselector" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ default 80 .Values.service.port }}
      targetPort: http
      {{- if and (eq (lower .Values.service.type) "nodeport") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}

{{- end }}