name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"      

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.9.0

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: true
  
      - name: Push docs to gh-pages
        run: |
          git checkout main
          find -name '*.md' > /tmp/readme_files
          git fetch origin gh-pages
          git checkout -B gh-pages origin/gh-pages
          git checkout main -- $(cat /tmp/readme_files)
          git add $(cat /tmp/readme_files)
          if [ -n "$(git diff --name-only --cached)" ]; then
            git commit -m 'Auto update documentation'
            git push origin gh-pages
          fi